name: 🐛 Bug Report
description: Reportar um bug ou comportamento inesperado
title: '[BUG] '
labels: ['bug', 'needs-triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 👋 Obrigado por reportar este bug!

        Preencha o formulário abaixo com o máximo de detalhes possível.
        Isso nos ajudará a reproduzir e corrigir o problema mais rapidamente.

  - type: textarea
    id: description
    attributes:
      label: 📝 Descrição do Bug
      description: Uma descrição clara e concisa do problema
      placeholder: 'Ex: Ao clicar no botão "Download SVG", nada acontece...'
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🔄 Passos para Reproduzir
      description: Como reproduzir o comportamento
      placeholder: |
        1. Vá para '...'
        2. Clique em '...'
        3. Role até '...'
        4. Veja o erro
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Comportamento Esperado
      description: O que você esperava que acontecesse?
      placeholder: 'Ex: O SVG deveria fazer download automaticamente...'
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ❌ Comportamento Atual
      description: O que realmente aconteceu?
      placeholder: 'Ex: Nada acontece quando clico no botão...'
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: 🌐 Navegador
      description: Em qual navegador o problema ocorre?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Opera
        - Outro
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: 📌 Versão do Navegador
      description: Qual a versão do seu navegador?
      placeholder: 'Ex: Chrome 120.0.6099.109'

  - type: dropdown
    id: device
    attributes:
      label: 📱 Dispositivo
      description: Em qual tipo de dispositivo o problema ocorre?
      options:
        - Desktop (Windows)
        - Desktop (Mac)
        - Desktop (Linux)
        - Mobile (Android)
        - Mobile (iOS)
        - Tablet
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Screenshots/Vídeos
      description: Se aplicável, adicione screenshots ou vídeos do problema
      placeholder: 'Cole URLs de imagens ou arraste arquivos aqui'

  - type: textarea
    id: console
    attributes:
      label: 🖥️ Logs do Console
      description: Abra o DevTools (F12) e cole os erros do console aqui
      render: javascript
      placeholder: |
        // Cole os erros do console aqui
        Error: Something went wrong...

  - type: input
    id: url
    attributes:
      label: 🔗 URL da Página
      description: Em qual página o problema ocorreu?
      placeholder: https://galeria-morallus.vercel.app/galeria/criar

  - type: textarea
    id: additional
    attributes:
      label: ℹ️ Contexto Adicional
      description: Adicione qualquer outro contexto sobre o problema aqui
      placeholder: 'Ex: O problema só ocorre quando...'

  - type: checkboxes
    id: terms
    attributes:
      label: ✅ Checklist
      description: Confirme os itens abaixo antes de enviar
      options:
        - label: Verifiquei que não existe uma issue similar já aberta
          required: true
        - label: Testei no navegador mais recente
          required: false
        - label: Tentei limpar o cache e cookies
          required: false
